-- Replace skills taxonomy with expanded grouped skill set.
delete from public.skills;

insert into public.skills (id, name, category, proficiency) values
  ('skill-001', 'Bubble', 'Web Development & No-Code Builders', 95),
  ('skill-002', 'Webflow', 'Web Development & No-Code Builders', 95),
  ('skill-003', 'Lovable', 'Web Development & No-Code Builders', 90),
  ('skill-004', 'Next.js', 'Web Development & No-Code Builders', 95),
  ('skill-005', 'React.js', 'Web Development & No-Code Builders', 95),
  ('skill-006', 'Django', 'Web Development & No-Code Builders', 92),
  ('skill-007', 'Laravel', 'Web Development & No-Code Builders', 90),
  ('skill-008', 'WordPress', 'Web Development & No-Code Builders', 90),
  ('skill-009', 'FlutterFlow', 'Web Development & No-Code Builders', 92),
  ('skill-010', 'Website Builder', 'Web Development & No-Code Builders', 90),
  ('skill-011', 'Website Customization', 'Web Development & No-Code Builders', 92),
  ('skill-012', 'Website Integration', 'Web Development & No-Code Builders', 92),
  ('skill-013', 'Flutter', 'Mobile Development', 92),
  ('skill-014', 'FlutterFlow', 'Mobile Development', 90),
  ('skill-015', 'Mobile UI/UX Design', 'Mobile Development', 90),
  ('skill-016', 'Android App Development', 'Mobile Development', 88),
  ('skill-017', 'Google Play Deployment', 'Mobile Development', 88),
  ('skill-018', 'UI/UX Design', 'UI/UX Design', 93),
  ('skill-019', 'Dark Corporate UI/UX', 'UI/UX Design', 90),
  ('skill-020', 'Mobile UI/UX Design', 'UI/UX Design', 90),
  ('skill-021', 'Landing Page Design', 'UI/UX Design', 92),
  ('skill-022', 'Web Design', 'UI/UX Design', 92),
  ('skill-023', 'Responsive Design', 'UI/UX Design', 95),
  ('skill-024', 'Arabic RTL Layout', 'UI/UX Design', 88),
  ('skill-025', 'Node.js', 'Backend & Database', 94),
  ('skill-026', 'Django', 'Backend & Database', 92),
  ('skill-027', 'Laravel', 'Backend & Database', 90),
  ('skill-028', 'REST API', 'Backend & Database', 94),
  ('skill-029', 'PostgreSQL', 'Backend & Database', 93),
  ('skill-030', 'MongoDB', 'Backend & Database', 92),
  ('skill-031', 'Cloud Hosting', 'Backend & Database', 90),
  ('skill-032', 'AI Agent Development', 'AI Development & Automation', 95),
  ('skill-033', 'AI App Development', 'AI Development & Automation', 94),
  ('skill-034', 'Generative AI Software', 'AI Development & Automation', 92),
  ('skill-035', 'AI Platform', 'AI Development & Automation', 92),
  ('skill-036', 'ChatGPT', 'AI Development & Automation', 95),
  ('skill-037', 'OpenAI API', 'AI Development & Automation', 95),
  ('skill-038', 'n8n', 'AI Development & Automation', 95),
  ('skill-039', 'Make.com', 'AI Development & Automation', 93),
  ('skill-040', 'Zapier', 'AI Development & Automation', 95),
  ('skill-041', 'Email Automation', 'AI Development & Automation', 92),
  ('skill-042', 'CRM Automation', 'AI Development & Automation', 92),
  ('skill-043', 'Automated Workflow', 'AI Development & Automation', 94),
  ('skill-044', 'Prompt Engineering', 'AI Development & Automation', 95),
  ('skill-045', 'Natural Language Processing (NLP)', 'AI Development & Automation', 90),
  ('skill-046', 'Machine Learning', 'AI Development & Automation', 88),
  ('skill-047', 'Artificial Intelligence', 'AI Development & Automation', 92),
  ('skill-048', 'Business Intelligence Software', 'AI Development & Automation', 88),
  ('skill-049', 'AI Speech-to-Text', 'Voice AI & Conversational AI', 93),
  ('skill-050', 'AI Text-to-Speech', 'Voice AI & Conversational AI', 93),
  ('skill-051', 'AI Voice Agent', 'Voice AI & Conversational AI', 92),
  ('skill-052', 'Twilio API', 'Voice AI & Conversational AI', 93),
  ('skill-053', 'WebSockets', 'Voice AI & Conversational AI', 92),
  ('skill-054', 'NLP Tokenization', 'Voice AI & Conversational AI', 88),
  ('skill-055', 'AI Bot', 'Voice AI & Conversational AI', 92),
  ('skill-056', 'AI Builder', 'Voice AI & Conversational AI', 90),
  ('skill-057', 'Cold Call Automation', 'Voice AI & Conversational AI', 88),
  ('skill-058', 'Real Estate Cold Calling', 'Voice AI & Conversational AI', 88),
  ('skill-059', 'GoHighLevel (GHL)', 'CRM & Marketing Automation', 94),
  ('skill-060', 'HighLevel', 'CRM & Marketing Automation', 94),
  ('skill-061', 'ClickFunnels', 'CRM & Marketing Automation', 90),
  ('skill-062', 'Sales Funnel', 'CRM & Marketing Automation', 92),
  ('skill-063', 'Sales Funnel Builder', 'CRM & Marketing Automation', 92),
  ('skill-064', 'Marketing Automation', 'CRM & Marketing Automation', 94),
  ('skill-065', 'CRM Software', 'CRM & Marketing Automation', 92),
  ('skill-066', 'CRM Automation', 'CRM & Marketing Automation', 94),
  ('skill-067', 'Email Design', 'CRM & Marketing Automation', 90),
  ('skill-068', 'Drip Campaign', 'CRM & Marketing Automation', 90),
  ('skill-069', 'Lead Generation', 'CRM & Marketing Automation', 92),
  ('skill-070', 'Podio', 'CRM & Marketing Automation', 88),
  ('skill-071', 'SaaS Development', 'SaaS & Software Development', 94),
  ('skill-072', 'SaaS', 'SaaS & Software Development', 92),
  ('skill-073', 'Software Development', 'SaaS & Software Development', 95),
  ('skill-074', 'AI-Powered SaaS', 'SaaS & Software Development', 92),
  ('skill-075', 'Custom Software', 'SaaS & Software Development', 92),
  ('skill-076', 'Application Development', 'SaaS & Software Development', 93),
  ('skill-077', 'Supabase', 'SaaS & Software Development', 92),
  ('skill-078', 'Python', 'SaaS & Software Development', 93),
  ('skill-079', 'Zapier', 'Integrations & Tools', 95),
  ('skill-080', 'Notion', 'Integrations & Tools', 90),
  ('skill-081', 'Shopify', 'Integrations & Tools', 90),
  ('skill-082', 'Trello', 'Integrations & Tools', 88),
  ('skill-083', 'Airtable', 'Integrations & Tools', 90),
  ('skill-084', 'Google Maps API', 'Integrations & Tools', 90),
  ('skill-085', 'Forex API', 'Integrations & Tools', 85),
  ('skill-086', 'Signal Feed', 'Integrations & Tools', 85),
  ('skill-087', 'Third-party API Integration', 'Integrations & Tools', 92),
  ('skill-088', 'SEO Content', 'SEO & Content', 90),
  ('skill-089', 'AI Content Detection', 'SEO & Content', 88),
  ('skill-090', 'Blog/CMS Setup', 'SEO & Content', 90),
  ('skill-091', 'Technical Copywriting', 'SEO & Content', 88),
  ('skill-092', 'Webflow Hosting', 'Deployment & Infrastructure', 90),
  ('skill-093', 'Cloud Deployment (AWS/Vercel)', 'Deployment & Infrastructure', 92),
  ('skill-094', 'Custom Domain Setup', 'Deployment & Infrastructure', 90),
  ('skill-095', 'SSL Configuration', 'Deployment & Infrastructure', 90),
  ('skill-096', 'Privacy Policy & Compliance', 'Deployment & Infrastructure', 86),
  ('skill-097', 'Google Play Console', 'Deployment & Infrastructure', 88);
